# Site settings
title: ChengLong's Blog
SEOTitle: ChengLong的技术博客 | 大模型技术研究
header-img: img/abstract-bg-02.jpg
email: chenglong799466@gmail.com
description: "专注于大模型技术研究与应用 | 云原生 | Kubernetes | Go"
keyword: "大模型, LLM, AI, Kubernetes, Go, Java, 云原生, 技术博客"
url: "https://chenglong799466.github.io"
baseurl: ""
github_repo: "https://github.com/chenglong799466/chenglong799466.github.io"

# Sidebar settings
sidebar: true
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-BY-gentle.jpg

# SNS settings
RSS: false
zhihu_username: kong-long-ge-39-72

# Build settings
permalink: pretty
paginate: 10
exclude: ["less","node_modules"]
anchorjs: true

# Plugins
plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 评论系统
gitalk:
  enable: false

# 统计
ba_track_id: b50bf2b12b5338a1845e33832976fd68
ga_track_id: 'UA-90855596-1'
ga_domain: auto

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#165DFF"
service-worker: true

# Friends
friends:
  - title: "Spring"
    href: "https://spring.io/"
  - title: "Java"
    href: "https://dev.java/"
  - title: "MySQL"
    href: "https://www.mysql.com/"
  - title: "Kubernetes"
    href: "https://kubernetes.io/"