# Site settings
title: Blog
SEOTitle: chenglong的博客 | CL Blog
header-img: img/abstract-bg-02.jpg
email: chenglong799466@gmail.com
description: "Every failure is leading towards success."
keyword: "CL Blog, chenglong的博客, chenglong, Go , Java"
url: "https://chenglong799466.github.io"
baseurl: ""
github_repo: "https://github.com/chenglong799466/chenglong799466.github.io"

# Available background images for posts and pages
# Options: img/post-bg-coffee.jpeg (default), img/abstract-bg-01.jpg, img/abstract-bg-02.jpg, 
# img/abstract-bg-03.jpg, img/nature-bg-04.jpg, img/nature-bg-05.jpg, img/nature-bg-06.jpg

# Sidebar settings
sidebar: true
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-BY-gentle.jpg

# SNS settings
RSS: false
zhihu_username: kong-long-ge-39-72

# Build settings
permalink: pretty
paginate: 10
exclude: ["less","node_modules"]
anchorjs: true

# Gems
gems: [jekyll-paginate]

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# 评论系统
gitalk:
  enable: false

# 统计
ba_track_id: b50bf2b12b5338a1845e33832976fd68
ga_track_id: 'UA-90855596-1'
ga_domain: auto

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends:
  - title: "spring"
    href: "https://spring.io/"
  - title: "java"
    href: "https://dev.java/"
  - title: "mysql"
    href: "https://www.mysql.com/"
  - title: "k8s"
    href: "https://kubernetes.io/"